# Generated by Django 3.2 on 2022-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_provider_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Список категорий',
                'ordering': ('-name',),
            },
        ),
    ]
