# Generated by Django 3.2 on 2023-01-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True, verbose_name='статус получения заказов'),
        ),
    ]
