# Generated by Django 3.2 on 2023-01-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderposition',
            options={'verbose_name': 'Заказанная позиция', 'verbose_name_plural': 'Список заказанных позиций'},
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='The User which is associated to this email confirmation'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='backend.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_positions', to='backend.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='backend.product', verbose_name='Продукт'),
        ),
        migrations.AddConstraint(
            model_name='orderposition',
            constraint=models.UniqueConstraint(fields=('order_id', 'product'), name='unique_order_item'),
        ),
    ]
