# Generated by Django 3.2 on 2023-01-15 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_customer_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_position',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.customer', to_field='user_id', verbose_name='Покупатель'),
        ),
    ]
