# Generated by Django 3.2 on 2023-01-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='ConfirmOrderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When was this token generated')),
                ('address', models.TextField()),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Key')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_order_tokens', to='backend.order', verbose_name='The Order which is associated to this confirmation')),
            ],
            options={
                'verbose_name': 'Токен подтверждения заказа',
                'verbose_name_plural': 'Токены подтверждения заказа',
            },
        ),
    ]
